fallback-handle: safestart:shutdown
plugins:
  - ==: com.mattmx.safestart.RequiredPlugin
    name: ViaBackwards
    handle: safestart:prevent_join
  - ==: com.mattmx.safestart.RequiredPlugin
    name: ViaVersion
    handle: safestart:prevent_join
